version: '3.8'

services:
  yollabi:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:3000/'
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - yollabi-network

networks:
  yollabi-network:
    driver: bridge
