version: '3.8'
services:
  yollabi:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_APP_URL: ${VITE_APP_URL}
        VITE_APP_DOMAIN: ${VITE_APP_DOMAIN}
    ports:
      - "3000:80"
    networks:
      - yollabi-network
networks:
  yollabi-network:
    driver: bridge
