version: '3.8'

services:
  yollabi:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      - yollabi-network
      - f4ggowkkswk4g4k8884cwsgc
networks:
  yollabi-network:
    driver: bridge
  f4ggowkkswk4g4k8884cwsgc:
    external: true