services:
  yollabi:
    build:
      context: .
    ports:
      - "3000:80"
    networks:
      - yollabi-network
    restart: always
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_APP_URL=${VITE_APP_URL}
      - VITE_APP_DOMAIN=${VITE_APP_DOMAIN}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  yollabi-network:
    driver: bridge
