version: '3.8'
services:
  yollabi:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_APP_URL=${VITE_APP_URL}
      - VITE_APP_DOMAIN=${VITE_APP_DOMAIN}
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      - yollabi-network
networks:
  yollabi-network:
    driver: bridge
